host: ""
port: 4000
tlsCert: "/etc/letsencrypt/live/mylesmoylan.net/fullchain.pem"
tlsKey: "/etc/letsencrypt/live/mylesmoylan.net/privkey.pem"
db:
    dsn: ""
    maxOpenConns: 25
    maxIdleConns: 25
    maxIdleTime: 15m
limiter:
    rps: 8
    burst: 16
    enabled: true
admin:
    username: ""
    passwordHash: ""
